plugins {
    id 'java'
    id("xyz.jpenilla.run-paper") version "2.3.1"

    id 'org.sonarqube' version '6.2.0.5505'
    id("com.gradleup.shadow") version "9.0.0-rc2"
}


group = 'de.emn4tor'
version = '1.0.0'

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
    maven { url 'https://jitpack.io' }
    maven{
        name = "nexo"
        url = "https://repo.nexomc.com/releases/"
    }
    maven { url "https://repo.codemc.org/repository/maven-public/" }
    maven { url "https://maven.enginehub.org/repo/" }
    repositories {
        maven {
            url = uri("https://repo.yellowmc.de/releases/")
            name = "api"
            credentials {
                username = System.getenv("YELLOWMC_USER")
                password = System.getenv("YELLOWMC_PASSWORD")
            }
        }
    }
}

dependencies {
    annotationProcessor("org.projectlombok:lombok:1.18.44")

    implementation("com.zaxxer:HikariCP:6.3.2")
    implementation("org.projectlombok:lombok:1.18.44")
    implementation("org.reflections:reflections:0.10.2")
    implementation("redis.clients:jedis:6.0.0")

    compileOnly("com.arcaniax:HeadDatabase-API:1.3.2")
    compileOnly("com.github.MilkBowl:VaultAPI:1.7.1")
    compileOnly("com.github.Septicuss:tooltips:1.8")
    compileOnly("com.nexomc:nexo:1.17.0")
    compileOnly("com.sk89q.worldedit:worldedit-bukkit:7.4.5")
    compileOnly("de.emn4tor:api:1.5.2-BETA")
    compileOnly("de.tr7zw:item-nbt-api-plugin:2.10.0")
    compileOnly("io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT")
    compileOnly("net.dmulloy2:ProtocolLib:5.4.0")
    compileOnly("net.luckperms:api:5.5")
    compileOnly("org.projectlombok:lombok:1.18.44")
}

tasks {
    runServer {
        // Configure the Minecraft version for our task.
        // This is the only required configuration besides applying the plugin.
        // Your plugin's jar (or shadowJar if present) will be used automatically.
        minecraftVersion("1.21.11")
    }
}

def targetJavaVersion = 21
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}

shadowJar {
    exclude 'META-INF/LICENSE', 'META-INF/LICENSE.txt', 'META-INF/NOTICE', 'META-INF/NOTICE.txt'
    mergeServiceFiles()
}

sonar {
    properties {
        property "sonar.projectKey", "YellowMC-Core"
    }
}



build.dependsOn shadowJar
