server-name: "Server"

credentials:
  database:
    url: "jdbc:mysql://localhost:3306/core_db?useSSL=false"
    user: devuser
    password: "123"
  redis:
    host: localhost
    port: 6379
    password:

hikari:
  maximumPoolSize: 10
  minimumIdle: 2
  connectionTimeout: 30000
  idleTimeout: 600000
  leakDetectionThreshold: 2000

furniture:
  enabled: false
